### ISSUE TITLE
[Setting] 프로젝트 초기세팅

### ISSUE THREAD

**Issue by binisnil** [Team-Motivoo/Motivoo-iOS#1]
### 🔥PURPOSE
> 프로젝트의 초기 세팅을 진행합니다
### 📒TODO
1. [x] 폴더링
2. [x] 이슈 템플릿
3. [x] PR 템플릿
4. [x] 디자인 시스템 적용
5. [x] BaseViewController, BaseView 만들기
6. [x] extension 추가해두기
7. [ ] 네트워크 관련 초기세팅 해두기
