### ISSUE TITLE
[Chore] QA 후 온보딩 변경 사항

### ISSUE THREAD

**Issue by LeeJoEun-01** [Team-Motivoo/Motivoo-iOS#103]
### 🔥PURPOSE
> 

### 📒TODO
1. [x] [이용약관] 글자 눌러도 동의되게 변경 가능? -> 이거 안돼요!
2. [x] 정보 수정 불가 뷰 추가
3. [x] [별명] 에러메세지 4초간 띄우는걸로 변경
4. [x] [나이] 나이 텍스트필드 패딩값 적용
5. [x] [온보딩] CTA 버튼 마진값 확인 구다사이
6. [x] [소셜 로그인] 로고 전달드릴게여 바꿔주세용가리
