### ISSUE TITLE
[Feat] 접근권한&이용약관 UI 제작

### ISSUE THREAD

**Issue by LeeJoEun-01** [Team-Motivoo/Motivoo-iOS#23]
### 🔥PURPOSE
> 
온보딩 단계 전에 있는 접근 권한 뷰와 이용 약관 UI 제작

### 📒TODO
1. [x] 접근 권한 UI
2. [x] 이용 약관 UI
3. [x] login&splash UI 수정
