### ISSUE TITLE
[Chore] 온보딩 디자인 수정사항 반영

### ISSUE THREAD

**Issue by LeeJoEun-01** [Team-Motivoo/Motivoo-iOS#44]
### 🔥PURPOSE
> 

### 📒TODO
1. [x] 온보딩 - 코드 입력하기 페이지 사진 추가
2. [x] 로그인 - 로그인 실패 label 추가
3. [x] 스플래시 로티 애니메이션 추가
7. [x] progressbar 수정
8. [x] 노션 페이지 링크 추가
