### ISSUE TITLE
[Fix] 온보딩 및 로그인, 로그아웃, 탈퇴하기 로직 수정

### ISSUE THREAD

**Issue by LeeJoEun-01** [Team-Motivoo/Motivoo-iOS#55]
### 🔥PURPOSE
> 

### 📒TODO
1. [ ]  온보딩 백버튼
2. [ ] 온보딩 부모 자녀 이슈
3. [x] 로그아웃 시 userDefault 삭제 X
4. [x] 회원탈퇴 시 userDefault 삭제 O
5. [x] back swipe 추가 구현
6. [x] QA: 로그인후 페이지 그래픽 수정
7. [x] 앱아이콘 추가
