### ISSUE TITLE
[Refactor] HomeView 관련 코드 수정

### ISSUE THREAD

**Issue by binisnil** [Team-Motivoo/Motivoo-iOS#68]
### 🔥PURPOSE
> 멘토님께 피드백받은 내용을 바탕으로 코드를 수정합니다.

### 📒TODO
1. [ ] 깡 MVC 내에서 VC의 로직을 덜어서 ViewModel로 만들기
2. [ ] MVVM-C : 여기에 코디네이터 객체 한스푼 넣기
3. [ ] Combine이나 Rx 같은 요소를 넣어서 비동기 이벤트 스트림 처리하기
4. [ ] 네트워크 부분을 Repository 패턴으로 변경해서 구현하기
5. [ ] 아래 먼저 시작...!
6. [ ] ViewModel로 분리하는 연습 (Input / Output 잘 구별하기)
7. [ ] 네트워크 레이어를 Repository 형태로 프로토콜 분리해서 해보기
8. [ ] 의존성 주입 개념 공부하기
9. [ ] 아키텍처 공부 및 적용
