### ISSUE TITLE
[Chore] 온보딩 수정사항 반영

### ISSUE THREAD

**Issue by LeeJoEun-01** [Team-Motivoo/Motivoo-iOS#87]
### 🔥PURPOSE
> 

### 📒TODO
1. [x] 온보딩 시 이름 입력 단계 추가
2. [x] 온보딩 API 수정
3. [x] 앱아이콘 추가
4. [ ] 애플 로그인 API 수정
