### ISSUE TITLE
[Chore] 온보딩 수정사항 반영

### ISSUE THREAD

**Issue by LeeJoEun-01** [Team-Motivoo/Motivoo-iOS#95]
### 🔥PURPOSE
> 

### 📒TODO
1. [x]  온보딩 시 이름 입력 단계 추가
2. [x] 온보딩 API 수정
3. [x] 애플 로그인 API 수정
4. [x] APPIcon 변경
