### ISSUE TITLE
[Chore] 모아보기 이슈 수정

### ISSUE THREAD

**Issue by LeeJoEun-01** [Team-Motivoo/Motivoo-iOS#98]
### 🔥PURPOSE
> 

### 📒TODO
1. [x] 히스토리 미션 3줄까지 가능
2. [x] `운동하러 가기` 버튼 클릭
3. [ ] 툴팁 보여지는 방식 변경
